### ISSUE TITLE
ovos-g2p-plugin-heuristic-arpa ERROR

### ISSUE THREAD

**Issue by aka0kuro** [OpenVoiceOS/raspbian-ovos#109]
I have the following error in ovos-audio WARNING - Could not find the plugin PluginTypes.PHONEME.ovos-g2p-plugin-heuristic-arpa
ERROR - The selected G2P plugin could not be loaded.
Traceback (most recent call last):
File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_plugin_manager/[g2p.py](http://g2p.py/)", line 139, in create
g2p = clazz(g2p_config)
^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
2023-12-07 10:07:17.981 - audio - ovos_plugin_manager.templates.tts:init:203 - ERROR - G2P plugin not loaded, there will be no mouth movements
Traceback (most recent call last):
File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_plugin_manager/templates/[tts.py](http://tts.py/)", line 201, in init
self.g2p = OVOSG2PFactory.create(cfg)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_plugin_manager/[g2p.py](http://g2p.py/)", line 139, in create
g2p = clazz(g2p_config)
^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable

**Comment by builderjer** [comment]
That plugin is not installed by default. It is used for mouth movements and is not necessary. 

That being said, I'm not sure why it is looking for it in the first place. I have not had that warning. Did you try and install a plugin or skill?

**Comment by denics** [comment]
sorry to bump in, but I am facing the same issue, it seems that the plugin is requested by the default mycroft.conf https://github.com/OpenVoiceOS/ovos-config/blob/dev/ovos_config/mycroft.conf#L732C3-L735C5

**Comment by builderjer** [comment]
It gets overridden here. I'm not sure why you are getting the error. I guess you can just install it, or I will include it in the next image. 

https://github.com/OpenVoiceOS/raspOVOS/blob/dev/stage-core%2F01-ovos-core%2Ffiles%2Fmycroft.conf#L45
