### ISSUE TITLE
Unable to use OCP radio skills like somafm - likely is user error

### ISSUE THREAD

**Issue by Bulwagga** [OpenVoiceOS/raspbian-ovos#50]
I have tried to use several radio skills and ovos_plugin_common_play with no success. Using somafm as an example, I have included my log files.

My mycroft.conf file includes:
`  "Audio": {
    "backends": {
      "local": {
        "type": "ovos_common_play",
        "active": true
      },
      "simple": {
        "type": "ovos_audio_simple",
        "active": true
      }
    },
    "default-backend": "local"
  }
`

espeak-ng is installed. 

My skills include:
ovos-ocp-m3u-plugin
ovos-tts-plugin-mimic
skill-ovos-somafm

The audio.log includes the suspicious, saying it cannot load the ovos-tts-plugin-mimic:
`2022-12-22 06:56:39.973 - audio - ovos_plugin_manager.tts:create:181 - INFO - Loaded plugin ovos-tts-plugin-piper
2022-12-22 06:56:39.987 - audio - ovos_audio.service:_maybe_reload_tts:299 - INFO - (re)loading fallback TTS engine
2022-12-22 06:56:40.184 - audio - ovos_config.models:load_local:105 - DEBUG - Configuration /home/ovos/.config/mycroft
/web_cache.json loaded
2022-12-22 06:56:40.478 - audio - ovos_plugin_manager.utils:load_plugin:132 - WARNING - Could not find the plugin mycr
oft.plugin.tts.ovos-tts-plugin-mimic
2022-12-22 06:56:40.742 - audio - ovos_plugin_manager.tts:create:187 - ERROR - The TTS plugin "ovos-tts-plugin-mimic" 
could not be loaded.
Available modules: ovos-tts-plugin-mimic3-server,ovos-tts-plugin-dummy,ovos-tts-plugin-piper
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/ovos_plugin_manager/tts.py", line 183, in create
    raise FileNotFoundError("unknown plugin")
FileNotFoundError: unknown plugin
2022-12-22 06:56:40.750 - audio - ovos_audio.service:__init__:76 - ERROR - unknown plugin
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/ovos_audio/service.py", line 73, in __init__
    self._maybe_reload_tts()
  File "/usr/local/lib/python3.9/dist-packages/ovos_audio/service.py", line 300, in _maybe_reload_tts
    self._get_tts_fallback()
  File "/usr/local/lib/python3.9/dist-packages/ovos_audio/service.py", line 327, in _get_tts_fallback
    self.fallback_tts = TTSFactory.create(cfg)
  File "/usr/local/lib/python3.9/dist-packages/ovos_audio/tts.py", line 9, in create
    return OVOSTTSFactory.create(config)
  File "/usr/local/lib/python3.9/dist-packages/ovos_plugin_manager/tts.py", line 183, in create
    raise FileNotFoundError("unknown plugin")
FileNotFoundError: unknown plugin
2022-12-22 06:56:40.761 - audio - ovos_audio.service:on_error:34 - ERROR - Audio service failed to launch (unknown plu
gin).
2022-12-22 06:56:41.111 - audio - ovos_plugin_manager.audio:load_audio_service_plugins:61 - INFO - Loading audio servi
ce plugin: ovos_common_play
`

[audio.log](https://github.com/OpenVoiceOS/raspbian-ovos/files/11507865/audio.log)
[ovos.log](https://github.com/OpenVoiceOS/raspbian-ovos/files/11507867/ovos.log)
[skills.log](https://github.com/OpenVoiceOS/raspbian-ovos/files/11507868/skills.log)

**Comment by Bulwagga** [comment]
pip install ovos-tts-plugin-mimic will install the plugin. I learned though that this entire direction I've taken to run audio services is fragile and not preferred.  I'm marking this closed.

**Comment by Bulwagga** [comment]
Maybe this approach would have worked if I had continued, but this is not the consensus approach for the future system.
